account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'

urlpatterns = [
	# URL-адрес профиля пользователя.
	path('profile/', views.profile, name='profile'),

	# URL-адрес регистрации.
	path('register/', views.register, name='register'),

	# URL-адреса входа и выхода.
	path('login/', auth_views.LoginView.as_view(), name='login'),
	path('logout/', views.logout_view, name='logout'),

	# URL-адреса смены пароля.
	path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name='password_change'),
	path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

	# URL-адреса сброса пароля.
	path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
	path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('password-reset/<uid64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

	# URL-адрес для добавления токенов.
	path('add_tokens/<int:user_id>/', views.add_tokens, name='add_tokens'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('account/', include('account.urls', namespace='account')),
    path('functions/', include('functions.urls', namespace='functions'))
]

dashboard/urls.py
"""Configurations URL for dashboard app."""

from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
	path('', views.dashboard, name='dashboard'),
	path('about/', views.about, name='about'),
]

functions/urls.py
from django.urls import path

from . import views

app_name = 'functions'

urlpatterns = [
	path('', views.FunctionsView.as_view(), name='functions'),
	path('ask_question_chatgpt/', views.AskQuestionChatGPTView.as_view(), name='ask_question_chatgpt'),
	path('upload_document/', views.UploadDocument.as_view(), name='upload_document'),
	path('delete_document/<int:pk>/', views.delete_document, name='delete_document'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	client_id_token = models.CharField(max_length=255, blank=True, null=True)
	client_secret_token = models.CharField(max_length=255, blank=True, null=True)
	chatgpt_token = models.CharField(max_length=255, blank=True, null=True)

functions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

import os


class ChatGPTDocument(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	document = models.FileField(upload_to=f'documents/%Y/%m/%d/%h', verbose_name='Документ')


	def delete(self, *args, **kwargs):
		if self.document:
			if os.path.isfile(self.document.path):
				os.remove(self.document.path)
		super().delete(*args, **kwargs)
		

account/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class UserRegistrationForm(forms.ModelForm):
	password = forms.CharField(label='Пароль',
								widget=forms.PasswordInput)
	password2 = forms.CharField(label='Повторите пароль',
								widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email']

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password'] != cd['password2']:
			raise forms.ValidationError("Passwords don't match.")
		return cd['password2']


class AddTokensForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['client_id_token', 'client_secret_token', 'chatgpt_token']

functions/forms.py
from django import forms

from .models import ChatGPTDocument


class AskQuestionChatGPTForm(forms.Form):
	text = forms.CharField(widget=forms.Textarea, label='Текст')


class ChatGPTDocumentForm(forms.ModelForm):
	class Meta:
		model = ChatGPTDocument
		fields = ['document']

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

from .models import Profile
from .forms import UserRegistrationForm, AddTokensForm


def register(request):
	if request.method == 'POST':
		user_form = UserRegistrationForm(request.POST)
		if user_form.is_valid():
			# Создаем новый обьект пользователя, но пока не сохраняем его.
			new_user = user_form.save(commit=False)
			# Установить выбранный пароль.
			new_user.set_password(user_form.cleaned_data['password'])
			# Сохранить обьект User.
			new_user.save()
			# Создаем обьект Profile.
			Profile.objects.create(user=new_user)
			# Вход в систему под новым аккаунтом.
			login(request, new_user)

			return render(request, 'account/register_done.html', {'new_user': new_user})
	else:
		user_form = UserRegistrationForm()
	return render(request, 'account/register.html', {'user_form': user_form})

    
def logout_view(request):
	logout(request)
	return redirect('dashboard:dashboard')


@login_required
def profile(request):
	return render(request, 'account/profile.html')


@require_POST
def add_tokens(request, user_id):
	"""Добавить токены в БД."""
	add_tokens_form = AddTokensForm(request.POST)
	if add_tokens_form.is_valid():
		data = add_tokens_form.data
		profile = Profile.objects.filter(user=user_id).first()
		profile.client_id_token = data['client_id_token']
		profile.client_secret_token = data['client_secret_token']
		profile.chatgpt_token = data['chatgpt_token']
		profile.save()
	else:
		# Ошибка.
		pass
	return redirect('account:profile')

dashboard/views.py
from django.shortcuts import render


def dashboard(request):
	return render(request, 'dashboard/dashboard.html')

def about(request):
	return render(request, 'dashboard/about.html')

functions/views.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404

from .models import ChatGPTDocument
from .forms import AskQuestionChatGPTForm, ChatGPTDocumentForm

from .chatgpt import upload_file_for_training, make_request_in_chatgpt

import requests


class FunctionsView(View):
	template_name = 'functions/functions.html'

	def get(self, request):
		return render(request, self.template_name)


class AskQuestionChatGPTView(View):
	template_name = 'functions/ask_question_chatgpt.html'

	def get(self, request):
		form = AskQuestionChatGPTForm(request.GET)
		text = form.data.get('text')

		if text:
			answer = make_request_in_chatgpt(text)
		else:
			answer = 'Вы не ввели текст'

		if request.user.profile.chatgpt_token:
			context = {'form': form, 'answer': answer, 'section': 'chatgpt'}
			return render(request, self.template_name, context)

		else:
			context = {'form': form, 'answer': answer, 'section': 'profile'}
			return render(request, self.template_name, context)


class UploadDocument(View):
	template_name = 'functions/upload_document.html'

	def post(self, request):
		form = ChatGPTDocumentForm(files=request.FILES)

		if form.is_valid():
			new_document = form.save(commit=False)
			new_document.user = request.user
			new_document.save()

			# Тренируем ChatGPT с помощью переданного файла.
			upload_file_for_training(new_document.document, request.user.profile.chatgpt_token)
			new_document.document.close()

		return render(request, self.template_name, {'form': form})


	def get(self, request):
		form = ChatGPTDocumentForm()
		return render(request, self.template_name, {'form': form})


def delete_document(request, pk):
	chatgptdocument = get_object_or_404(ChatGPTDocument, pk=pk)
	chatgptdocument.delete()

	return redirect('functions:upload_document')

dashboard/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>officeGPT {% block title %}{% endblock %}</title>
	<!-- Bootstrap css. -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
	<!-- My static. -->
	<link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

	{% block links %}
	{% endblock %}
</head>
<body>
	<div class="container">
		<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
			<a href="{% url 'dashboard:dashboard' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
				<svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
        		<span class="fs-4">officeGPT</span>
			</a>

      		<ul class="nav nav-pills">
        		<li class="nav-item"><a href="{% url 'dashboard:dashboard' %}" class="nav-link active" aria-current="page">Dashboard</a></li>
        		<li class="nav-item"><a href="{% url 'functions:functions' %}" class="nav-link">Функции</a></li>
        		<!-- Проверяем, зарегестрирован пользователь или нет. -->
				{% if request.user.is_authenticated %}
					{% if request.user.first_name %}
        				<li class="nav-item"><a href="{% url 'account:profile' %}" class="nav-link">{{ request.user.first_name }}</a></li>
        			{% else %}
        				<li class="nav-item"><a href="{% url 'account:profile' %}" class="nav-link">{{ request.user.get_username }}</a></li>
        			{% endif %}
        			<li class="nav-item"><a href="{% url 'account:logout' %}" class="nav-link">Выйти</a></li>
        		{% else %}
        			<li class="nav-item"><a href="{% url 'account:register' %}" class="nav-link">Зарегестрироваться</a></li>
        			<li class="nav-item"><a href="{% url 'account:login' %}" class="nav-link">Войти</a></li>
        		{% endif %}
        		<li class="nav-item"><a href="{% url 'dashboard:about' %}" class="nav-link">О нас</a></li>
      		</ul>
    	</header>
  	</div>

	<div class="content">
		{% block content %}
		{% endblock %}
	</div>

	<footer class="footer mt-auto py-3 bg-light">
		<div class="container">
			<span class="text-muted">© 2023 officegpt.ru</span>
		</div>
	</footer>

	<!-- Bootstrap js. -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

	<!-- Подключение скриптов Bootstrap (jQuery и Popper.js) -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

dashboard/templates/dashboard/about.html
{% extends 'base.html' %}

{% block content %}
	<div class="container mt-5">
		<div class="row">
			<div class="col-lg-8 offset-lg-2">
				<h2 class="text-center mb-4">Наш инновационный онлайн-сервис</h2>
				<p class="lead text-justify">Представляет собой мощное решение для компаний, стремящихся оптимизировать свои взаимодействия в B2B сегменте. Мы интегрируем платформы Avito, WhatsApp, Telegram и email с возможностями искусственного интеллекта ChatGPT, создавая централизованную систему для автоматической обработки и управления входящими бизнес-запросами. Эта система не только ускоряет и упрощает коммуникацию между бизнесами, но и предоставляет продвинутые аналитические инструменты для глубокого понимания потребностей и предпочтений клиентов.</p>

				<h3 class="mt-4">Особенности и Преимущества:</h3>
				<ul>
			    	<li>Автоматизация и Упрощение Коммуникаций: Уникальная интеграция с ChatGPT позволяет автоматически обрабатывать запросы и сообщения, сокращая время ответа и повышая эффективность коммуникаций.</li>
			    	<li>Масштабируемость и Гибкость: Сервис легко масштабируется для удовлетворения потребностей как малого, так и крупного бизнеса, обеспечивая гибкость в обработке большого объема запросов.</li>
			    	<li>Улучшенное Управление Клиентскими Отношениями (CRM): Интеграция с CRM системами позволяет лучше понимать клиентов и управлять взаимоотношениями, оптимизируя маркетинговые и продажные стратегии.</li>
			    	<li>Аналитика и Инсайты: Сервис предоставляет ценные данные и аналитику, помогающую компаниям принимать обоснованные бизнес-решения, основанные на поведении и предпочтениях их клиентов.</li>
			    	<li>Конфиденциальность и Безопасность Данных: Высокий уровень безопасности и конфиденциальности данных гарантирует, что вся клиентская информация защищена и обрабатывается в соответствии с нормативными требованиями.</li>
			    	<li>Поддержка Множества Языков: Поддержка различных языков расширяет возможности международного бизнес-взаимодействия, делая сервис доступным для разнообразной клиентуры.</li>
			  	</ul>

			  	<h3 class="mt-4">Почему Компании Должны Выбрать Наш Сервис:</h3>
			  	<ul>
			    	<li>Производительность и Эффективность: Наш сервис значительно повышает производительность, автоматизируя рутинные задачи и позволяя сотрудникам сосредоточиться на более важных аспектах бизнеса.</li>
			    	<li>Улучшенное Взаимодействие с Клиентами: Благодаря персонализированным и своевременным ответам укрепляется доверие и лояльность клиентов.</li>
			    	<li>Стратегическое Преимущество: Использование данных и аналитики для определения бизнес-трендов и принятия стратегических решений дает компаниям конкурентное преимущество на рынке.</li>
			  	</ul>

			  	<p class="text-justify mt-4">Этот сервис идеально подходит для компаний, стремящихся повысить свою конкурентоспособность и эффективность, используя передовые технологии в области искусственного интеллекта и автоматизации бизнес-процессов.</p>
			</div>
		</div>
	</div>
{% endblock %}

dashboard/templates/dashboard/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<div class="container mt-5">
		<div class="row">
			<div class="col-lg-8 offset-lg-2">
				<h2 class="text-center mb-4">Dashboard</h2>
			</div>
		</div>
	</div>
{% endblock %}

functions/templates/functions/ask_question_chatgpt.html
{% extends 'base.html' %}

{% block title %}Задать вопрос ChatGPT{% endblock %}

{% block content %}
	{% if section == 'chatgpt' %}
		<div class="container mt-5">
			<div class="row">
				<div class="col-lg-6">
					<h2 class="text-center mb-4">Задать вопрос ChatGPT</h2>
					<p>Текст:</p>
					<form method="get">
						{{ form.text }}
						<p><input type="submit" value="Задать вопрос"></p>
					</form>
				</div>
	
				<div class="col-lg-6">
					{% if answer %}
						<h2 class="mb-4">Ответ от ChatGPT</h2>
						<p>{{ answer }}</p>
					{% endif %}
				</div>
			</div>
		</div>
	{% else %}
		<div class="container mt-5">
			<div class="row">
				<div class="col-lg-6">
					<h2 class="text-center mb-4">Заполните профиль</h2>
					<p class="lead text-justify">Пожалуйста, перед тем как задать вопрос ChatGPT, сначала добавьте токены на странице <a href="{% url 'account:profile' %}">профиля</a>! Пожалуйста, введите только настоящие данные.</p>
				</div>
			</div>
		</div>
	{% endif %}
{% endblock %}

functions/templates/functions/functions.html
{% extends 'base.html' %}

{% block title %}Функции{% endblock %}

{% block content %}
	<div class="container mt-5">
		<div class="row">
			<div class="col-lg-8 offset-lg-2">
				<h2 class="text-center mb-4">Функции</h2>
				<p class="lead text-justify">Ниже приведены все функции проекта officeGPT с их описаниями. Знайте, что некоторые из них доступны только после регистрации и заполнения профиля.</p>

				<h3 class="mt-4">Функции:</h3>
				<ul>
					<li><a href="{% url 'functions:ask_question_chatgpt' %}">Задать вопрос у ChatGPT</a></li>
					<li><a href="{% url 'functions:upload_document' %}">Добавить документ (txt) файл для обучения ChatGPT</a></li>
				</ul>

			</div>
		</div>
	</div>
{% endblock %}

functions/templates/functions/upload_document.html
{% extends 'base.html' %}

{% block title %}Загрузить документ{% endblock %}

{% block content %}
	<div class="container mt-5">
		<div class="row">
			<!-- Пользователь уже добавил документ. Возвращаем добавленный документ и даем возможность удалить документ для добавления нового. -->
			{% if request.user.chatgptdocument.document %}
				<div class="col-lg-8 offset-lg-2">
					<h2 class="text-center mb-4">Документ уже добавлен</h2>
					<p class="lead text-justify">Вы уже добавили документ. Каждый пользователь может добавить только по 1 документу. Если вас не устраивает ваш добавленный документ, вы можете <a href="{% url 'functions:delete_document' request.user.chatgptdocument.id %}">удалить его</a> и затем уже добавить другой на этой же странице.</p>
				</div>
			{% else %}
				<div class="col-lg-8 offset-lg-2">
					<h2 class="text-center mb-4">Добавить документ</h2>
					<p class="lead text-justify">Загрузите пожалуйста файл с расширение txt, который содержит информацию с помощью которой ChatGPT сможет более подробно отвечать на ваши вопросы и не только.</p>
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{{ form.as_p }}
						<button type="submit">Загрузить</button>
					</form>
				</div>
			{% endif %}
		</div>
	</div>
{% endblock %}